export const CURRENT_USER = "CURRENT_USER";
export const CLEAR_USER = "CLEAR_USER";
export const INITIALIZE_FRIENDS_POSTS = "INITIALIZE_FRIENDS_POSTS";
export const ADD_USER = "ADD_USER";

export const SHIFT_LAST_TEN = "SHIFT_LAST_TEN";
export const PUSH_LAST_TEN = "PUSH_LAST_TEN";

export const SEND_POST = "SEND_POST";

export const REMOVE_FRIEND = "REMOVE_FRIEND";
export const UPDATE_REMOVED_FRIENDS_POSTS = "UPDATE_REMOVED_FRIENDS_POSTS";
export const UPDATE_ADDED_FRIENDS_POSTS = "UPDATE_ADDED_FRIENDS_POSTS";
export const ADD_FRIEND = "ADD_FRIEND";
